apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-httproute
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
    sectionName: web
  rules:
  # {{ .Values.path }} pathprefix
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.path }}
    backendRefs:
    - name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.port }}
    filters:
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: {{ .Release.Name }}-stripprefix
  # root "/" path
  - matches:
    - path:
        type: Exact
        value: /
    filters:
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: {{ .Release.Name }}-redirect-root

---

# Strip {{ .Values.path }} prefix before forwarding requests to whoami
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-stripprefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.path }}

---

# Redirect / to {{ .Values.path }}, only triggered when root path / is requested
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-redirect-root
spec:
  redirectRegex:
    regex: /$
    replacement: {{ .Values.path }}
