apiVersion: v2
name: argo-workflows
description: Argo Workflows
type: application
version: 0.1.0
appVersion: "v3.5.11"
dependencies:
  - name: argo-workflows
    version: 0.42.5
    repository: https://argoproj.github.io/argo-helm
